### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by flareso** [Hanggi/ethers#1]
look on this guy implementation 
https://github.com/FAME-Capital/ethers_flutter

he didnt finished it, but the way is much better

**Comment by Hanggi** [comment]
Yes, I will update the package when I have time.

Thank you and I have looked at the package, it is using flutter_js which could run js code directly.

Buf after looking up some bechmarks I found that it was not that performant.
So I just want to make a pure dart version.

I would consider the way of implementation.
